### PR TITLE
doc: add Chinese version

### PR DESCRIPTION
**Pull request by lusipad**
add Simplified Chinese version, include:

- add floder "Chinese"
- use douban[^1] to replace amazon links

[^1]: a Chinese website allows registered users to record information and create content related to film, books, music, recent events

### CODE REVIEW

**Comment by salmer** [comment]
Ho @lusipad. Are you finished with this PR? Can I start reviewing it and "merge to master"?

**Comment by lusipad** [comment]
> Ho @lusipad. Are you finished with this PR? Can I start reviewing it and "merge to master"? 

yes

**Comment by DmitrievDmitriyA** [comment]
@lusipad Nicely done! I've found a broken link, but I will fix it once the PR is merged. 
Thank you very much for the effort!

I was wondering, could you also help to translate the Miro map? I want to create a Chinese version and use it in the text instead of the English one.

**Comment by DmitrievDmitriyA** [comment]
@lusipad Nicely done! I've found a broken link, but I will fix it once the PR is merged. 
Thank you very much for the effort!

I was wondering, could you also help to translate the Miro map? Chinese version could be created as

**Comment by DmitrievDmitriyA** [comment]
@lusipad Nicely done! I've found a broken link, but I will fix it once the PR is merged. 
Thank you very much for the effort!

I was wondering, could you also help to translate the Miro map? I want to create a Chinese version, so it could be used in the text instead of the English one.

**Comment by lusipad** [comment]
> @lusipad Nicely done! I've found a broken link, but I will fix it once the PR is merged. Thank you very much for the effort!
> 
> I was wondering, could you also help to translate the Miro map? I want to create a Chinese version, so it could be used in the text instead of the English one.

Sure. However, I think some technical terms may be more commonly expressed in English, so I'll do my best to provide a bilingual translation.

**Comment by DmitrievDmitriyA** [comment]
> > @lusipad Nicely done! I've found a broken link, but I will fix it once the PR is merged. Thank you very much for the effort!
> > I was wondering, could you also help to translate the Miro map? I want to create a Chinese version, so it could be used in the text instead of the English one.
> 
> Sure. However, I think some technical terms may be more commonly expressed in English, so I'll do my best to provide a bilingual translation.

Yes, sure. It's up to you to translate it in a native way cuz you can speak it 👍🏻 
I have invited you to the Miro team using the email mentioned in you profile.
Let me know if you have access to https://miro.com/app/board/uXjVMQjliUg=/ and can edit it

**Pull request merged**
